name: dfdb
version: '0.2.0'
maintainer: Dan Fithian
license: Apache-2.0
copyright: 2020 Dan Fithian

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -eventlog
  - -O0

default-extensions:
  - ConstraintKinds
  - DeriveGeneric
  - DataKinds
  - DeriveDataTypeable
  - DerivingStrategies
  - DerivingVia
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedLabels
  - OverloadedStrings
  - PartialTypeSignatures
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns

dependencies:
  - aeson
  - attoparsec
  - base
  - bytestring
  - classy-prelude
  - directory
  - hspec
  - lens
  - mtl

library:
  source-dirs:
    - src

executables:
  dfdb:
    main: main.hs
    source-dirs:
      - app
    dependencies:
      - dfdb
    ghc-options:
      - -optP-Wno-nonportable-include-path
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'

  index-bench:
    main: index-bench.hs
    source-dirs:
      - app
    dependencies:
      - criterion
      - QuickCheck
      - dfdb
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'

tests:
  test:
    main: main.hs
    source-dirs:
      - test
    dependencies:
      - QuickCheck
      - dfdb
